const data = [
  {
    id: "01",
    archetypeName: "The Explorer",
    archetypeMotto: "Don't fence me in.",
    archetypeDesire:
      "the freedom to find out who you are through exploring the world.",
    archetypeGoal:
      "to experience a better, more authentic, more fulfilling life.",
    archetypeFear: ["getting trapped", "conformity", "inner emptiness"],
    archetypeStrategy: [
      "journey",
      "seeking out and experiencing new things",
      "escape from boredom",
    ],
    archetypeWeakness: ["aimless wandering", "becoming a misfit."],
    archetypeTalent: ["autonomy", "ambition", "being true to one's soul"],
    archetypeOtherName: [
      "The seeker",
      "Iconoclas",
      "Wanderer",
      "Individualist",
      "Pilgrim",
    ],
    cardinalOrientation: "Soul",
  },
  {
    id: "02",
    archetypeName: "The Sage",
    archetypeMotto: "The truth will set you free.",
    archetypeDesire: " to find the truth.",
    archetypeGoal: "to use intelligence and analysis to understand the world.",
    archetypeFear: ["being duped", "misled", "ignorance"],
    archetypeStrategy: [
      "seeking out information",
      " knowledge",
      "self-reflection",
      "understanding thought processes",
    ],
    archetypeWeakness: "can study details forever and never act.",
    archetypeTalent: ["wisdom", "intelligence"],
    archetypeOtherName: [
      "The expert",
      "Scholar",
      "Detective",
      "Advisor",
      "Thinker",
      "Philosopher",
      "Academic",
      "Researcher",
      "Planner",
      "Professional",
      "Mentor",
      "Teacher",
      "Contemplative",
    ],
    cardinalOrientation: "Self",
  },
  {
    id: "03",
    archetypeName: "The Innocent",
    archetypeMotto: "Free to be you and me.",
    archetypeDesire: "to get to paradise.",
    archetypeGoal: "to make dreams come true.",
    archetypeFear: "to be punished for doing something bad or wrong.",
    archetypeStrategy: "to do things right.",
    archetypeWeakness: ["boring for all", "naive innocence"],
    archetypeTalent: ["faith", "optimism"],
    archetypeOtherName: [
      "Utopian",
      "Traditionalist",
      "Naive",
      "Mystic",
      "Saint",
      "Romantic",
      "Dreamer",
    ],
    cardinalOrientation: "Ego",
  },
  {
    id: "04",
    archetypeName: "The Hero",
    archetypeMotto: "Where there's a will, there's a way.",
    archetypeDesire: "to prove one's worth through courageous acts.",
    archetypeGoal: "expert mastery in a way that improves the world.",
    archetypeFear: ["weakness", "vulnerability", "being a Chicken"],
    archetypeStrategy: ["to be as strong", "competent as possible."],
    archetypeWeakness: ["arrogance", "always needing another battle to fight."],
    archetypeTalent: ["competence", "courage"],
    archetypeOtherName: [
      "The warrior",
      "Crusader",
      "Rescuer",
      "Superhero",
      "The Soldier",
      "The Slayer",
      "The Winner",
      "The Team Player",
    ],
    cardinalOrientation: "Ego",
  },
  {
    id: "05",
    archetypeName: "The Magician",
    archetypeMotto: "I make things happen.",
    archetypeDesire: "understanding the fundamental laws of the universe.",
    archetypeGoal: "to make dreams come true.",
    archetypeFear: ["unintended negative consequences"],
    archetypeStrategy: ["develop a vision and live by it"],
    archetypeWeakness: ["becoming manipulative"],
    archetypeTalent: ["finding win-win solutions."],
    archetypeOtherName: [
      "The visionary",
      "Catalyst",
      "Inventor",
      "Charismatic Leader",
      "Shaman",
      "Healer",
      "Medicine Man",
    ],
    cardinalOrientation: "Self",
  },
  {
    id: "06",
    archetypeName: "The Outlaw",
    archetypeMotto: "Rules are made to be broken.",
    archetypeDesire: ["Revenge", "Revolution"],
    archetypeGoal: "to overturn what isn't working.",
    archetypeFear: ["Powerless", "Ineffectual"],
    archetypeStrategy: ["Disrupt", "Destroy", "Shock"],
    archetypeWeakness: ["Crossing over to the dark side", "crime"],
    archetypeTalent: ["Outrageousness", "Radical Freedom"],
    archetypeOtherName: [
      "The Rebel",
      "Revolutionary",
      "Wild Man",
      "The Misfit",
      "Iconoclast",
    ],
    cardinalOrientation: "Soul",
  },
  {
    id: "07",
    archetypeName: "The Everyman",
    archetypeMotto: "All men and women are created equal.",
    archetypeDesire: ["Connecting with others"],
    archetypeGoal: "To belong.",
    archetypeFear: ["To be left out", "To stand out from the crowd"],
    archetypeStrategy: [
      "Develop ordinary solid virtues",
      "Be down to earth",
      "The common touch",
    ],
    archetypeWeakness: [
      "Losing one's own self in an effort to blend in or for the sake of superficial relationships.",
    ],
    archetypeTalent: ["Realism", "Empathy", "Lack of Pretense"],
    archetypeOtherName: [
      "The Regular Guy/Girl",
      "The good old boy",
      "The person next door",
      "The Realist",
      "The working stiff",
      "The solid citizen",
      "The Good Neighbor",
      "The silent",
    ],
    cardinalOrientation: "Ego",
  },
  {
    id: "08",
    archetypeName: "The Joker",
    archetypeMotto: "You only live once.",
    archetypeDesire: ["To live in the moment with full enjoyment."],
    archetypeGoal: "To have a great time and lighten up the world.",
    archetypeFear: ["Being bored", "Boring others"],
    archetypeStrategy: ["Play", "Make Jokes", "Be Funny"],
    archetypeWeakness: ["Frivolity", "Wasting time"],
    archetypeTalent: ["Joy"],
    archetypeOtherName: [
      "The Jester",
      "Entertainer",
      "The fool",
      "Trickster",
      "Practical Jokester",
      "Comedian.",
    ],
    cardinalOrientation: "Self",
  },
  {
    id: "09",
    archetypeName: "The Lover",
    archetypeMotto: "You're the only one.",
    archetypeDesire: ["Intimacy", "Experience"],
    archetypeGoal:
      "Being in a relationship with the people, work and surroundings they love.",
    archetypeFear: ["Being alone", "A Wallflower", "Unwanted", "Unloved"],
    archetypeStrategy: [
      "To become more and more physically and emotionally attractive.",
    ],
    archetypeWeakness: [
      "Outward-directed desire to please others at risk of losing own identity.",
    ],
    archetypeTalent: ["Passion", "Gratitude", "Appreciation", "Commitment"],
    archetypeOtherName: [
      "The Partner",
      "Friend",
      "Intimate",
      "Enthusiast",
      "Sensualist",
      "Spouse",
      "Team-builder",
    ],
    cardinalOrientation: "Soul",
  },
  {
    id: "10",
    archetypeName: "The Creator",
    archetypeMotto: "If you can imagine it, it can be done.",
    archetypeDesire: ["To create things of enduring value."],
    archetypeGoal: "To realize a vision.",
    archetypeFear: ["Mediocre vision", "Mediocre execution"],
    archetypeStrategy: [
      "Develop artistic control",
      "Develop artistic skill",
      "To create culture",
      "Express own vision",
    ],
    archetypeWeakness: ["Perfectionism", "Bad solutions"],
    archetypeTalent: ["Creativity", "Imagination"],
    archetypeOtherName: [
      "The artist",
      "Inventor",
      "Innovator",
      "Musician",
      "Writer",
      "Dreamer",
    ],
    cardinalOrientation: "Soul",
  },
  {
    id: "11",
    archetypeName: "The Ruler",
    archetypeMotto: "Power isn't everything, it's the only thing.",
    archetypeDesire: ["Control"],
    archetypeGoal: "Create a prosperous, successful family or community.",
    archetypeFear: ["Chaos", "Being overthrown"],
    archetypeStrategy: ["Exercise power"],
    archetypeWeakness: ["Being authoritarian", "Unable to delegate"],
    archetypeTalent: ["Responsibility", "Leadership"],
    archetypeOtherName: [
      "The boss",
      "Leader",
      "Aristocrat",
      "King",
      "Queen",
      "Politician",
      "Role model",
      "Manager",
      "Administrator",
    ],
    cardinalOrientation: "Self",
  },
  {
    id: "12",
    archetypeName: "The Caregiver",
    archetypeMotto: "Love your neighbour as yourself.",
    archetypeDesire: ["To protect", "Care for others"],
    archetypeGoal: "To help others.",
    archetypeFear: ["Selfishness", "Ingratitude"],
    archetypeStrategy: ["Doing things for others"],
    archetypeWeakness: ["Martyrdom", "Being exploited"],
    archetypeTalent: ["Compassion", "Generosity"],
    archetypeOtherName: [
      "The saint",
      "Altruist",
      "Parent",
      "Helper",
      "Supporter",
    ],
    cardinalOrientation: "Ego",
  },
];

export default data;
